### ISSUE TITLE
Separate the animation library from the controls / GIF renderer

### ISSUE THREAD

**Issue by msurguy** [bit101/gifloopcoder#4]
In my opinion, this product could be separated in 3 separate downloadable pieces that could be used together if necessary:

- The animation engine
- The GIF encoder
- The UI

The pros of this is that anybody could use the library on their website without downloading the GIF encoder and UI that they might not need to use.

**Comment by msurguy** [comment]
There's also an existing library that seems to incorporate similar pieces that are used here. Maybe there is a chance to pull that in as a dependency instead of creating a duplicate inside of this lib.

Here's the existing lib: https://github.com/jnordberg/gif.js

**Comment by bit101** [comment]
This is not a direction I want to go with the project. The animation engine is not optimized enough for a general animation engine. Almost every possible property of the canvas is reset for every object on every frame. It can really start slowing down once you get a lot of objects in there. This doesn't really matter due to the fact that once it's rendered to gif, that problem goes away. If I were going to make a general purpose animation library, I'd start from scratch with a different strategy. 

The gif encoder is not my code, but taken from other open source libraries. So I wouldn't republish that. 

The UI is useless without the other pieces.
